version: "2017-09-20"
pipeline:
  - id: build
    type: script
    commands:
    - desc: 'Install required build software'
      cmd: 'apt-get install -y make git apt-transport-https ca-certificates curl'
    - desc: 'Install Docker'
      cmd: 'curl -sSL https://delivery.cloud.zalando.com/utils/ensure-docker | sh'
    - desc: 'Build'
      cmd: |
        image=ubuntu-temp:${CDP_BUILD_VERSION}
        docker build -t $image --squash .
        sed -i "s,UNTESTED,$image,g" Dockerfile.test
        docker build -t $image-test -f Dockerfile.test .
        # get current LSB release (/etc/lsb-release)
        out=$(docker run $image-test)
        echo $out
        eval "$out"
        # e.g. "Ubuntu 16.04.3 LTS"
        version=$(echo $DISTRIB_DESCRIPTION | awk '{ print $2}')
        release=registry-write.opensource.zalan.do/stups/ubuntu:$version-${CDP_TARGET_BRANCH_COUNTER}
        IS_PR_BUILD=${CDP_PULL_REQUEST_NUMBER+"true"}
        if [[ $CDP_TARGET_BRANCH == "master" && ${IS_PR_BUILD} != "true" ]]
        then
            docker tag $image $release
            docker push $release
        fi
